server: 
  port: 8081
  servlet: 
    context-path: /resource-server

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dips-as.herokuapp.com/auth/realms/DIPS/
          jwk-set-uri: https://dips-as.herokuapp.com/auth/realms/DIPS/protocol/openid-connect/certs